config:
#  switch:
#    name: hub1
#    ipv4: 192.168.2.20/24
#    interfaces: 
#      - eth1
#      - eth2
#      - eth3
  router:
    interfaces:
      eth1:
        ipv4: 192.168.10.1/24
      eth2:
        ipv4: 192.168.20.1/24
